// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9btmadAFxm-D7r8K7zhKBBb0p4X3Fso',
    appId: '1:600908153185:web:9f3685c7962bfb73e80520',
    messagingSenderId: '600908153185',
    projectId: 'exitoxy-398e0',
    authDomain: 'exitoxy-398e0.firebaseapp.com',
    storageBucket: 'exitoxy-398e0.firebasestorage.app',
    measurementId: 'G-CDB3R6E8GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYIsrxqqrYZd2hlE2KFMawFOKua57QNcI',
    appId: '1:600908153185:android:94138d32f8302250e80520',
    messagingSenderId: '600908153185',
    projectId: 'exitoxy-398e0',
    storageBucket: 'exitoxy-398e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsfE7ETpyh3xwpFHduRnOYZYo2PK5Y1q0',
    appId: '1:600908153185:ios:7c798afa64195cbfe80520',
    messagingSenderId: '600908153185',
    projectId: 'exitoxy-398e0',
    storageBucket: 'exitoxy-398e0.firebasestorage.app',
    iosBundleId: 'com.example.kitit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsfE7ETpyh3xwpFHduRnOYZYo2PK5Y1q0',
    appId: '1:600908153185:ios:7c798afa64195cbfe80520',
    messagingSenderId: '600908153185',
    projectId: 'exitoxy-398e0',
    storageBucket: 'exitoxy-398e0.firebasestorage.app',
    iosBundleId: 'com.example.kitit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9btmadAFxm-D7r8K7zhKBBb0p4X3Fso',
    appId: '1:600908153185:web:f669a52a514ffb51e80520',
    messagingSenderId: '600908153185',
    projectId: 'exitoxy-398e0',
    authDomain: 'exitoxy-398e0.firebaseapp.com',
    storageBucket: 'exitoxy-398e0.firebasestorage.app',
    measurementId: 'G-VGMCN1YHGV',
  );
}
